---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant1helmrelease1
  namespace: tenant1
spec:
  chart:
    spec:
      chart: ./tenant1app
      interval: 30m0s
      sourceRef:
        kind: GitRepository
        name: tenant1helmrepo
        namespace: tenant1
      version: 1.0.0
  install:
    remediation:
      retries: 3
  interval: 30m0s
  test:
    enable: true
    ignoreFailures: true
  driftDetection:
    mode: enabled
  releaseName: tenant1helmrelease1
  targetNamespace: tenant1
  timeout: 30m0s
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: "1.26"
    nameOverride: ""
    fullnameOverride: ""
    replicaCount: 5
    serviceAccount:
      create: true
      annotations: {}
      name: ""
    service:
      type: ClusterIP
      port: 80
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tenant1helmrepo
  namespace: tenant1
spec:
  interval: 30m0s
  ref:
    commit: 4eacb5681a8b5197a9c50e452ef21de320010d01
  url: https://github.com/fk-gitops/helm-repo
